// fh1: RECTANGLE_LIST -> quad. Generated by tools/fh1_make_rect_gs.py; do not edit by hand.
struct V
{
    float4 pos : SV_Position;
    [[vk::location(0)]] float4 v0 : TEXCOORD0;
    [[vk::location(1)]] float4 v1 : TEXCOORD1;
    [[vk::location(2)]] float4 v2 : TEXCOORD2;
    [[vk::location(3)]] float4 v3 : TEXCOORD3;
    [[vk::location(4)]] float4 v4 : TEXCOORD4;
    [[vk::location(5)]] float4 v5 : TEXCOORD5;
    [[vk::location(6)]] float4 v6 : TEXCOORD6;
    [[vk::location(7)]] float4 v7 : TEXCOORD7;
    [[vk::location(8)]] float4 v8 : TEXCOORD8;
    [[vk::location(9)]] float4 v9 : TEXCOORD9;
    [[vk::location(10)]] float4 v10 : TEXCOORD10;
    [[vk::location(11)]] float4 v11 : TEXCOORD11;
    [[vk::location(12)]] float4 v12 : TEXCOORD12;
    [[vk::location(13)]] float4 v13 : TEXCOORD13;
    [[vk::location(14)]] float4 v14 : TEXCOORD14;
    [[vk::location(15)]] float4 v15 : TEXCOORD15;
    [[vk::location(16)]] float4 v16 : COLOR0;
    [[vk::location(17)]] float4 v17 : COLOR1;
    [[vk::location(18)]] float4 v18 : COLOR2;
    [[vk::location(19)]] float4 v19 : COLOR3;
    [[vk::location(20)]] float4 v20 : COLOR4;
    [[vk::location(21)]] float4 v21 : COLOR5;
    [[vk::location(22)]] float4 v22 : FOG0;
    [[vk::location(23)]] float4 v23 : NORMAL0;
};

// The fourth vertex of the rectangle whose corner a lies between b and c.
V Fourth(V a, V b, V c)
{
    V o;
    o.pos = b.pos + c.pos - a.pos;
    o.v0 = b.v0 + c.v0 - a.v0;
    o.v1 = b.v1 + c.v1 - a.v1;
    o.v2 = b.v2 + c.v2 - a.v2;
    o.v3 = b.v3 + c.v3 - a.v3;
    o.v4 = b.v4 + c.v4 - a.v4;
    o.v5 = b.v5 + c.v5 - a.v5;
    o.v6 = b.v6 + c.v6 - a.v6;
    o.v7 = b.v7 + c.v7 - a.v7;
    o.v8 = b.v8 + c.v8 - a.v8;
    o.v9 = b.v9 + c.v9 - a.v9;
    o.v10 = b.v10 + c.v10 - a.v10;
    o.v11 = b.v11 + c.v11 - a.v11;
    o.v12 = b.v12 + c.v12 - a.v12;
    o.v13 = b.v13 + c.v13 - a.v13;
    o.v14 = b.v14 + c.v14 - a.v14;
    o.v15 = b.v15 + c.v15 - a.v15;
    o.v16 = b.v16 + c.v16 - a.v16;
    o.v17 = b.v17 + c.v17 - a.v17;
    o.v18 = b.v18 + c.v18 - a.v18;
    o.v19 = b.v19 + c.v19 - a.v19;
    o.v20 = b.v20 + c.v20 - a.v20;
    o.v21 = b.v21 + c.v21 - a.v21;
    o.v22 = b.v22 + c.v22 - a.v22;
    o.v23 = b.v23 + c.v23 - a.v23;
    return o;
}

float Length2(float4 a, float4 b)
{
    float2 d = a.xy / a.w - b.xy / b.w;
    return dot(d, d);
}

[maxvertexcount(4)]
void main(triangle V input[3], inout TriangleStream<V> stream)
{
    // The corner is opposite the longest edge. The strip starts at the corner and keeps the winding of the draw.
    float e01 = Length2(input[0].pos, input[1].pos);
    float e12 = Length2(input[1].pos, input[2].pos);
    float e20 = Length2(input[2].pos, input[0].pos);
    uint corner = 0;
    if (e20 > e12 && e20 >= e01)
    {
        corner = 1;
    }
    else if (e01 > e12 && e01 > e20)
    {
        corner = 2;
    }
    V a = input[corner];
    V b = input[(corner + 1) % 3];
    V c = input[(corner + 2) % 3];
    stream.Append(a);
    stream.Append(b);
    stream.Append(c);
    stream.Append(Fourth(a, b, c));
    stream.RestartStrip();
}
