// fh1: resolved depth + stencil -> the console's bytes in an 8-bit color image.
// Generated by tools/fh1_make_depth_pack.py; do not edit by hand.
[[vk::binding(0, 0)]] Texture2D<float> g_Depth;
[[vk::binding(1, 0)]] Texture2D<uint> g_Stencil;

struct Push
{
    uint float24;  // 1: 24-bit float depth (D24FS8); 0: 24-bit integer depth (D24S8)
};
[[vk::push_constant]] Push g_Push;

float4 VsMain(uint id : SV_VertexID) : SV_Position
{
    return float4(float((id << 1) & 2) * 2.0 - 1.0, float(id & 2) * 2.0 - 1.0, 0.0, 1.0);
}

// The console's 20e4 float from a 32-bit float, rounded to nearest even (xenos::Float32To20e4).
uint Float24(float depth)
{
    uint f = asuint(depth);
    f = min(f <= 0x7FFFFFFFu ? f : 0u, 0x3FFFFFF8u);
    uint denormal = ((f & 0x7FFFFFu) | 0x800000u) >> min(113u - (f >> 23), 24u);
    uint f24 = f < 0x38800000u ? denormal : f + 0xC8000000u;
    f24 += 3u + ((f24 >> 3) & 1u);
    return (f24 >> 3) & 0xFFFFFFu;
}

float4 PsMain(float4 position : SV_Position) : SV_Target0
{
    int3 texel = int3(int2(position.xy), 0);
    float depth = g_Depth.Load(texel);
    uint stencil = g_Stencil.Load(texel) & 0xFFu;
    // min: a depth of exactly 1 gives 16777216 in 32-bit float arithmetic, one past the 24 bits (bytes FF 00 00
    // instead of FF FF FF: a mask the game fills with Z = 1 came out with green and blue at 0).
    uint bits = g_Push.float24 != 0u ? Float24(depth)
                                     : min(uint(saturate(depth) * 16777215.0 + 0.5), 0xFFFFFFu);
    return float4(float(stencil), float(bits & 0xFFu), float((bits >> 8) & 0xFFu), float(bits >> 16)) / 255.0;
}
