#!/usr/bin/env python3
"""Generates the "depth as bytes" shaders of FH1's native renderer and embeds their SPIR-V.

FH1 resolves the scene depth to a texture and two post-processing shaders (the motion-blur velocity and the
depth-of-field input) fetch that texture as k_8_8_8_8: they rebuild the 24-bit depth from its three bytes and take
the stencil from the fourth (the stencil picks the object's previous-frame matrix). On the console the resolve
writes those bytes to memory. Here a resolved depth is a host depth image, so this pass writes the same bytes into
an 8-bit color image the first time a draw fetches the depth that way after a resolve.

Output texel (red, green, blue, alpha) = (stencil, depth bits 0-7, depth bits 8-15, depth bits 16-23), the bytes of
the console's 32-bit word (depth << 8 | stencil) from the lowest up; the fetch constant's swizzle does the rest.
The depth is the console's 24-bit float (20e4) or 24-bit integer, by the push constant.

Usage (repo root): python tools/fh1_make_depth_pack.py [path to a SPIR-V-enabled dxc.exe]
Default dxc: ..\\tools_dxc\\bin\\x64\\dxc.exe. Writes shaders/fh1_depth_pack.hlsl and
fh1/src/native/fh1_depth_pack_spirv.h (not game-derived: committed).
"""
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

HLSL = '''// fh1: resolved depth + stencil -> the console's bytes in an 8-bit color image.
// Generated by tools/fh1_make_depth_pack.py; do not edit by hand.
[[vk::binding(0, 0)]] Texture2D<float> g_Depth;
[[vk::binding(1, 0)]] Texture2D<uint> g_Stencil;

struct Push
{
    uint float24;  // 1: 24-bit float depth (D24FS8); 0: 24-bit integer depth (D24S8)
};
[[vk::push_constant]] Push g_Push;

float4 VsMain(uint id : SV_VertexID) : SV_Position
{
    return float4(float((id << 1) & 2) * 2.0 - 1.0, float(id & 2) * 2.0 - 1.0, 0.0, 1.0);
}

// The console's 20e4 float from a 32-bit float, rounded to nearest even (xenos::Float32To20e4).
uint Float24(float depth)
{
    uint f = asuint(depth);
    f = min(f <= 0x7FFFFFFFu ? f : 0u, 0x3FFFFFF8u);
    uint denormal = ((f & 0x7FFFFFu) | 0x800000u) >> min(113u - (f >> 23), 24u);
    uint f24 = f < 0x38800000u ? denormal : f + 0xC8000000u;
    f24 += 3u + ((f24 >> 3) & 1u);
    return (f24 >> 3) & 0xFFFFFFu;
}

float4 PsMain(float4 position : SV_Position) : SV_Target0
{
    int3 texel = int3(int2(position.xy), 0);
    float depth = g_Depth.Load(texel);
    uint stencil = g_Stencil.Load(texel) & 0xFFu;
    uint bits = g_Push.float24 != 0u ? Float24(depth)
                                     : uint(saturate(depth) * 16777215.0 + 0.5);
    return float4(float(stencil), float(bits & 0xFFu), float((bits >> 8) & 0xFFu), float(bits >> 16)) / 255.0;
}
'''


def compile_stage(dxc, hlsl_path, profile, entry):
    out = os.path.join(tempfile.gettempdir(), 'fh1_depth_pack_%s.spv' % entry)
    subprocess.check_call([dxc, '-spirv', '-T', profile, '-E', entry, '-HV', '2021', '-fspv-target-env=vulkan1.2',
                           '-Fo', out, hlsl_path])
    data = open(out, 'rb').read()
    words = struct.unpack('<%dI' % (len(data) // 4), data)
    lines = []
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join('0x%08X' % w for w in words[i:i + 8]) + ',')
    return '\n'.join(lines), len(words)


def main():
    dxc = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '..', 'tools_dxc', 'bin', 'x64', 'dxc.exe')
    hlsl_path = os.path.join(ROOT, 'shaders', 'fh1_depth_pack.hlsl')
    open(hlsl_path, 'w', newline='\n').write(HLSL)
    vs, n_vs = compile_stage(dxc, hlsl_path, 'vs_6_0', 'VsMain')
    ps, n_ps = compile_stage(dxc, hlsl_path, 'ps_6_0', 'PsMain')
    header = ('// fh1: SPIR-V of shaders/fh1_depth_pack.hlsl (resolved depth + stencil as the console\'s bytes).\n'
              '// Generated by tools/fh1_make_depth_pack.py; do not edit by hand.\n#pragma once\n#include <cstdint>\n\n'
              'namespace fh1 {\ninline constexpr uint32_t kDepthPackVsSpirv[] = {\n%s\n};\n'
              'inline constexpr uint32_t kDepthPackPsSpirv[] = {\n%s\n};\n}  // namespace fh1\n' % (vs, ps))
    open(os.path.join(ROOT, 'fh1', 'src', 'native', 'fh1_depth_pack_spirv.h'), 'w', newline='\n').write(header)
    print('wrote %d + %d SPIR-V words' % (n_vs, n_ps))


if __name__ == '__main__':
    main()
