#!/usr/bin/env python3
"""Generates the rectangle-list geometry shader of FH1's native renderer and embeds its SPIR-V.

The Xbox 360 GPU draws a RECTANGLE_LIST from 3 vertices per rectangle and computes the fourth corner itself, for
the position and every interpolant. Vulkan has no such topology, so the renderer draws the vertices as a triangle
list and this geometry shader emits the full quad as a triangle strip.

Which of the three vertices is the corner between the other two depends on the draw: FH1's clears send top-left,
top-right, bottom-right (the corner is the second vertex), its post-processing passes top-left, top-right,
bottom-left (the corner is the first). The corner is the vertex opposite the longest edge (the diagonal), and the
fourth vertex is the other two added minus the corner. nfsc-recomp's shader, the base of this one, always took the
first vertex as the corner: FH1's clears then covered only half of the screen.

The interface is the one every translated vertex shader has (shaders/XenosRecomp/shader_recompiler.cpp,
INTERPOLATORS): oPos, then TEXCOORD0..15, COLOR0..5, FOG0, NORMAL0 = 24 float4 outputs at locations 0..23.

Usage (repo root): python tools/fh1_make_rect_gs.py [path to a SPIR-V-enabled dxc.exe]
Default dxc: ..\\tools_dxc\\bin\\x64\\dxc.exe. Writes shaders/fh1_rect_gs.hlsl and
fh1/src/native/fh1_rect_gs_spirv.h (not game-derived: committed).
"""
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
NAMES = ['TEXCOORD%d' % i for i in range(16)] + ['COLOR%d' % i for i in range(6)] + ['FOG0', 'NORMAL0']


def main():
    dxc = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '..', 'tools_dxc', 'bin', 'x64', 'dxc.exe')
    members = ''.join('    [[vk::location(%d)]] float4 v%d : %s;\n' % (i, i, n) for i, n in enumerate(NAMES))
    mix = ''.join('    o.v%d = b.v%d + c.v%d - a.v%d;\n' % (i, i, i, i) for i in range(len(NAMES)))
    hlsl = '''// fh1: RECTANGLE_LIST -> quad. Generated by tools/fh1_make_rect_gs.py; do not edit by hand.
struct V
{
    float4 pos : SV_Position;
%s};

// The fourth vertex of the rectangle whose corner a lies between b and c.
V Fourth(V a, V b, V c)
{
    V o;
    o.pos = b.pos + c.pos - a.pos;
%s    return o;
}

float Length2(float4 a, float4 b)
{
    float2 d = a.xy / a.w - b.xy / b.w;
    return dot(d, d);
}

[maxvertexcount(4)]
void main(triangle V input[3], inout TriangleStream<V> stream)
{
    // The corner is opposite the longest edge. The strip starts at the corner and keeps the winding of the draw.
    float e01 = Length2(input[0].pos, input[1].pos);
    float e12 = Length2(input[1].pos, input[2].pos);
    float e20 = Length2(input[2].pos, input[0].pos);
    uint corner = 0;
    if (e20 > e12 && e20 >= e01)
    {
        corner = 1;
    }
    else if (e01 > e12 && e01 > e20)
    {
        corner = 2;
    }
    V a = input[corner];
    V b = input[(corner + 1) %% 3];
    V c = input[(corner + 2) %% 3];
    stream.Append(a);
    stream.Append(b);
    stream.Append(c);
    stream.Append(Fourth(a, b, c));
    stream.RestartStrip();
}
''' % (members, mix)
    hlsl_path = os.path.join(ROOT, 'shaders', 'fh1_rect_gs.hlsl')
    open(hlsl_path, 'w', newline='\n').write(hlsl)
    out = os.path.join(tempfile.gettempdir(), 'fh1_rect_gs.spv')
    subprocess.check_call([dxc, '-spirv', '-T', 'gs_6_6', '-E', 'main', '-HV', '2021', '-fspv-target-env=vulkan1.2',
                           '-fvk-use-dx-layout', '-Fo', out, hlsl_path])
    data = open(out, 'rb').read()
    words = struct.unpack('<%dI' % (len(data) // 4), data)
    lines = []
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join('0x%08X' % w for w in words[i:i + 8]) + ',')
    header = ('// fh1: SPIR-V of shaders/fh1_rect_gs.hlsl (RECTANGLE_LIST geometry shader). Generated by\n'
              '// tools/fh1_make_rect_gs.py; do not edit by hand.\n#pragma once\n#include <cstdint>\n\n'
              'namespace fh1 {\ninline constexpr uint32_t kRectGsSpirv[] = {\n%s\n};\n}  // namespace fh1\n' % '\n'.join(lines))
    open(os.path.join(ROOT, 'fh1', 'src', 'native', 'fh1_rect_gs_spirv.h'), 'w', newline='\n').write(header)
    print('wrote %d SPIR-V words' % len(words))


if __name__ == '__main__':
    main()
