#!/usr/bin/env python3
"""Generate fh1/src/fh1_d3d_census.cpp: a call counter on every translated function in the
address ranges where FH1's Direct3D lives (ROADMAP Stage 3, phase A: mapping the game's D3D).

With --fh1_d3d_census the game logs, every 10 s, the functions called most per frame (frames =
calls of the Swap function sub_829EFB30): draw functions show hundreds per frame, state setters
dozens, Present once. Off, each counter costs one predictable branch.

    python tools/gen_d3d_census.py        (needs fh1/generated, i.e. one codegen run)

Functions that already have a REX_HOOK_RAW in fh1/src are skipped (two strong definitions of the
same sub_ would not link). The output contains only addresses.
"""
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RANGES = [(0x823E0000, 0x82420000), (0x829D0000, 0x82A40000)]
SWAP = "829EFB30"

subprocess_needed = not os.path.exists(os.path.join(ROOT, "fh1", "generated", ".callgraph.json"))
if subprocess_needed:
    import subprocess
    import sys
    subprocess.run([sys.executable, os.path.join(ROOT, "tools", "callgraph.py"), "callers", SWAP],
                   check=True, stdout=subprocess.DEVNULL)
funcs = json.load(open(os.path.join(ROOT, "fh1", "generated", ".callgraph.json")))

hooked = set()
for path in glob.glob(os.path.join(ROOT, "fh1", "src", "*.cpp")):
    if path.endswith("fh1_d3d_census.cpp"):
        continue
    for m in re.finditer(r"REX_HOOK_RAW\(sub_([0-9A-F]{8})\)", open(path, encoding="utf-8").read()):
        hooked.add(m.group(1))

addrs = sorted(a for a in funcs if any(lo <= int(a, 16) < hi for lo, hi in RANGES) and a not in hooked)
swap_index = addrs.index(SWAP) if SWAP in addrs else -1

out = []
out.append("// fh1 - Direct3D census (GENERATED by tools/gen_d3d_census.py - do not edit by hand).")
out.append("// Counts calls of every function in FH1's Direct3D address ranges; --fh1_d3d_census logs the")
out.append("// most called per frame every 10 s. Phase A of the native renderer (ROADMAP Stage 3).")
out.append(f"// {len(addrs)} functions; skipped because hooked elsewhere: {', '.join(sorted(hooked & set(funcs))) or 'none'}")
out.append("")
out.append('#include "fh1_d3d_census.h"')
out.append("")
out.append("#include <rex/hook.h>")
out.append("")
out.append("namespace fh1::census {")
out.append(f"const uint32_t kAddresses[{len(addrs)}] = {{")
for i in range(0, len(addrs), 8):
    out.append("    " + ", ".join(f"0x{a}" for a in addrs[i:i + 8]) + ",")
out.append("};")
out.append(f"const uint32_t kCount = {len(addrs)};")
out.append(f"const int32_t kSwapIndex = {swap_index};")
out.append(f"std::atomic<uint32_t> g_calls[{len(addrs)}];")
out.append("}  // namespace fh1::census")
out.append("")
out.append("#define FH1_CENSUS(addr, idx)                                      \\")
out.append("  REX_EXTERN(__imp__sub_##addr);                                   \\")
out.append("  REX_HOOK_RAW(sub_##addr) {                                       \\")
out.append("    if (fh1::census::g_on.load(std::memory_order_relaxed)) {       \\")
out.append("      fh1::census::Count(idx, ctx);                                \\")
out.append("    }                                                              \\")
out.append("    __imp__sub_##addr(ctx, base);                                  \\")
out.append("  }")
out.append("")
for i, a in enumerate(addrs):
    out.append(f"FH1_CENSUS({a}, {i})")
out.append("")
open(os.path.join(ROOT, "fh1", "src", "fh1_d3d_census.cpp"), "w", newline="\n").write("\n".join(out))
print(f"{len(addrs)} functions, swap index {swap_index}, skipped {sorted(hooked & set(funcs))}")
