// fh1 - Direct3D census: call counts of every function in the game's D3D address ranges
// (counters generated by tools/gen_d3d_census.py into fh1_d3d_census.cpp; report in
// fh1_d3d_census_report.cpp). --fh1_d3d_census turns it on. ROADMAP Stage 3, phase A.
#pragma once

#include <atomic>
#include <cstdint>

#include <rex/ppc.h>

namespace fh1::census {

extern std::atomic<bool> g_on;
extern const uint32_t kAddresses[];
extern const uint32_t kCount;
extern const int32_t kSwapIndex;  // the Swap function: one call per frame
extern std::atomic<uint32_t> g_calls[];

void Count(uint32_t index, PPCContext& ctx);

}  // namespace fh1::census
